"""
Shared pytest configuration for this project.

- Report:      generated by the pytest-html plugin (see pytest.ini) into
               reports/report_api.html — a single self-contained file.
- Screenshots: for the UI suite (test_loan_calculator.py), pytest-playwright's
               built-in --screenshot/--video/--tracing flags (see pytest.ini)
               handle this automatically — no custom code needed. Captures
               land under test-results/<test-name>/.
- Logs:        every test run appends structured, timestamped lines to
               logs/test_run.log, configured here directly (not via
               pytest.ini, since ini's addopts splits on whitespace and
               a format string containing spaces breaks argument parsing).
               The API suite (test_posts_api.py) logs each request/response
               explicitly, since it has no browser to screenshot.
"""
import logging
import os

logger = logging.getLogger("test_framework")


def pytest_configure(config):
    os.makedirs("logs", exist_ok=True)
    os.makedirs("reports", exist_ok=True)

    file_handler = logging.FileHandler("logs/test_run.log", mode="a", encoding="utf-8")
    file_handler.setLevel(logging.INFO)
    file_handler.setFormatter(logging.Formatter(
        "%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    ))
    root_logger = logging.getLogger()
    root_logger.addHandler(file_handler)
    root_logger.setLevel(logging.INFO)


def pytest_runtest_logreport(report):
    # Fires once per test phase (setup/call/teardown); we only want one
    # summary line per test, so filter to the "call" phase.
    if report.when != "call":
        return
    duration = f"{report.duration:.2f}s"
    logger.info("%s | %s | %s", report.outcome.upper(), report.nodeid, duration)
    if report.failed:
        logger.error("FAILURE DETAILS for %s:\n%s", report.nodeid, report.longreprtext)
